
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\PFE\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("768x576")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 576,
    width = 768,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    743.0,
    532.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    686.0,
    532.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    39.0,
    29.0,
    image=image_image_3
)

canvas.create_text(
    714.0,
    551.0,
    anchor="nw",
    text="الاعدادات",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 16 * -1)
)

canvas.create_text(
    668.0,
    551.0,
    anchor="nw",
    text="المساعدة",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 16 * -1)
)

canvas.create_text(
    1142.0,
    338.0,
    anchor="nw",
    text="قائمة الطلبة",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 40 * -1)
)

canvas.create_text(
    653.0,
    0.0,
    anchor="nw",
    text="اضافة طالب",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 28 * -1)
)

canvas.create_rectangle(
    646.0,
    42.0,
    765.064826965332,
    44.0,
    fill="#000000",
    outline="")

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    43.0,
    532.0,
    image=image_image_4
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    532.5,
    94.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=457.0,
    y=77.0,
    width=151.0,
    height=32.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    533.5,
    161.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=458.0,
    y=144.0,
    width=151.0,
    height=32.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    533.5,
    288.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=458.0,
    y=271.0,
    width=151.0,
    height=32.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    533.5,
    345.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=458.0,
    y=328.0,
    width=151.0,
    height=32.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    533.5,
    402.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=458.0,
    y=385.0,
    width=151.0,
    height=32.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    134.5,
    94.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=59.0,
    y=77.0,
    width=151.0,
    height=32.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    134.5,
    161.0,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=59.0,
    y=144.0,
    width=151.0,
    height=32.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    134.5,
    288.0,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=59.0,
    y=271.0,
    width=151.0,
    height=32.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    134.5,
    228.0,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=59.0,
    y=211.0,
    width=151.0,
    height=32.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    532.5,
    228.0,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=457.0,
    y=211.0,
    width=151.0,
    height=32.0
)

canvas.create_rectangle(
    59.0,
    328.0,
    210.0,
    479.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    685.0,
    80.0,
    anchor="nw",
    text="الاسم",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    282.0,
    80.0,
    anchor="nw",
    text="مهنة الاب",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    285.0,
    147.0,
    anchor="nw",
    text="مهنة الام",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    302.0,
    274.0,
    anchor="nw",
    text="القسم",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    242.0,
    214.0,
    anchor="nw",
    text="البريد الالكتروني",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    685.0,
    144.0,
    anchor="nw",
    text="اللقب",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    654.0,
    217.0,
    anchor="nw",
    text="تاريخ الميلاد",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    656.0,
    271.0,
    anchor="nw",
    text="رقم الهاتف",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    685.0,
    328.0,
    anchor="nw",
    text="الجنس",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)

canvas.create_text(
    685.0,
    385.0,
    anchor="nw",
    text="العمر",
    fill="#000000",
    font=("ArefRuqaa Regular", 18 * -1)
)
window.resizable(False, False)
window.mainloop()
