
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage , StringVar


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\PFE\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("768x576")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 576,
    width = 768,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    743.0,
    532.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    686.0,
    532.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    39.0,
    29.0,
    image=image_image_3
)

canvas.create_text(
    714.0,
    551.0,
    anchor="nw",
    text="الاعدادات",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 16 * -1)
)

canvas.create_text(
    668.0,
    551.0,
    anchor="nw",
    text="المساعدة",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 16 * -1)
)

canvas.create_text(
    1142.0,
    338.0,
    anchor="nw",
    text="قائمة الطلبة",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 40 * -1)
)

canvas.create_text(
    321.0,
    123.0,
    anchor="nw",
    text="البحث في القائمة",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 28 * -1)
)

canvas.create_text(
    646.0,
    0.0,
    anchor="nw",
    text="تسيير الطلاب",
    fill="#4D4D4D",
    font=("ArefRuqaa Regular", 28 * -1)
)

canvas.create_rectangle(
    646.0,
    42.0,
    765.064826965332,
    44.0,
    fill="#000000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    384.5,
    194.0,
    image=entry_image_1
)
...

search_var = StringVar()
search_var.trace_add("write", lambda name, index, mode: clear_entry_widget(search_var,entry_1) if search_var.get() == "للبحث عن الشخص عليك بادخال اسمه..." else None)
entry_1 = Entry(
    bd=1,
    bg="#FFFFFF",
    fg="#000000",
    justify="right",
    textvariable=search_var,
    highlightthickness=2,
    highlightbackground="#1EA6A0",
)

...

def clear_entry_widget(entry_widget):
    initial_text = "للبحث عن الشخص عليك بادخال اسمه..."

    # If the text in the entry widget is the same as the initial text, clear it
    if entry_widget.get() == initial_text:
        entry_widget.delete(0, 'end')

    # If the entry widget is empty, insert the initial text
    elif entry_widget.get() == "":
        entry_widget.insert(0, initial_text)

...

entry_1.place(
    x=137.0,
    y=172.0,
    width=495.0,
    height=42.0
)

...

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=147.0,
    y=185.0,
    width=1.0,
    height=16.0
)

canvas.create_text(
    454.0,
    182.79248046875,
    anchor="nw",
    text="للبحث عن الشخص عليك بادخال اسمه...",
    fill="#000000",
    font=("ArefRuqaa Regular", 14 * -1)
)

canvas.create_rectangle(
    217.0,
    62.0,
    552.0,
    118.8956298828125,
    fill="#F2F2F2",
    outline="")

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    268.788330078125,
    90.4498291015625,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    361.7081298828125,
    90.4498291015625,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    507.2006530761719,
    90.4498291015625,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    436.2882080078125,
    90.4498291015625,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    43.0,
    532.0,
    image=image_image_8
)

canvas.create_rectangle(
    70.0,
    237.0,
    719.0,
    489.0,
    fill="#D9D9D9",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=369.0,
    y=442.9999990500553,
    width=40.375134182968395,
    height=41.191036664141905
)
window.resizable(False, False)
window.mainloop()
